### ISSUE TITLE
IP Restriction Docs: Potential Error

### ISSUE THREAD

**Issue by rawkode** [ngrok/ngrok-docs#1038]
I was trying to run the examples from the [Restrict IPs / Testing documentation](https://ngrok.com/docs/http/traffic-policy/actions/restrict-ips/#test-restricting-ips).

```yaml
on_http_request:
  - actions:
      - type: "restrict-ips"
        config:
          enforce: false
          ip_policies:
            - "ipp_1yjqdrIBwgciY2I9zH2EelgBbJF"
      - type: "log"
        config:
          metadata:
            message: "Restrict IPs action would be ${actions.ngrok.restrict_ips.action} for
              ${conn.client_ip}."
            matched_cidr: "${actions.ngrok.restrict_ips.matched_cidr}"
            error:
              code: "${actions.ngrok.restrict_ips.error.code}"
              message: "${actions.ngrok.restrict_ips.error.message}"
```

Unfortunately, I couldn't get it to work for the following reasons:

1. Can't use `type: "log"` after actions that deny the request.
2. `type: "log"` supports arbitrary metadata and the docs suggest that is an `string: any` type, but the ngrok cli fails to start as it expects string values `string: string`
