### ISSUE TITLE
Endpoints document is still using `tunnels` which is marked `deprecated` in Agent Config

### ISSUE THREAD

**Issue by southwolf** [ngrok/ngrok-docs#1045]
`tunnels` is marked as `deprecated` in [Agent Config](https://ngrok-docs-git-niji-agent-config-v3-ngrok-dev.vercel.app/docs/agent/config/v3/#tunnels-deprecated), but  
[Endpoints](https://ngrok-docs-git-niji-agent-config-v3-ngrok-dev.vercel.app/docs/http/?cty=agent-config#basic-usage) section is still using `tunnels` and has not migrated to `endpoints` yet. e.g.

```yaml
tunnels:
  example:
    proto: http
    addr: 8080
    domain: example.ngrok.app
```

Should be updated / migrated to

```yaml
endpoints:
  - name: example
    url: https://example.ngrok.app
    upstream:
      url: 8080
```

But I am not sure what is the best format to present. Should both `endpoints` & `tunnels` configurations be kept on the page but `tunnels` is marked `deprecated`? Or just remove `tunnels` and only leave `endpoints`?
