### ISSUE TITLE
Docs on traffic policy is wrong

### ISSUE THREAD

**Issue by gdoron** [ngrok/ngrok-docs#1260]
https://ngrok.com/docs/traffic-policy/getting-started/agent-endpoints/cli/

Running the example:

```
on_http_request:
  actions:
    type: custom-response
    config:
      status_code: 200
      content: Hello, World!
```

Yields this error

> ERROR:  failed to start tunnel: The TrafficPolicy you provided is invalid: could not decode from string: The traffic policy was not able to be parsed:
> ERROR:  line 2: received invalid value of type 'map' for traffic policy rule array..
> ERROR:
> ERROR:  ERR_NGROK_9026
> ERROR:  https://ngrok.com/docs/errors/err_ngrok_9026
> ERROR:

The correct config should be:

```
on_http_request:
  - actions:
      - type: custom-response
        config:
          status_code: 200
          headers:
            content-type: text/plain
          content: "Hello world!"
```
