### ISSUE TITLE
make anchors/links more robust to external script styling

### ISSUE THREAD

**Issue by cody-dot-js** [ngrok/ngrok-docs#393]
it appears that ketch (our external cookie consent solution) added some global styles which affected our docs links:

![image](https://github.com/ngrok/ngrok-docs/assets/34115417/0acd6d9b-a382-4831-b434-06f25e40c537)

we should add the following css to each selector that matches a unique anchor:

```css
.xxx {
  text-decoration: none;
}
.xxx:hover {
  text-decoration: underline;
}
.xxx:focus {
  text-decoration: underline;
}
```

This should (probably) apply to the following selectors:
- `navbar__link`
- `menu__link`
- `menu__link--sublist`
- `breadcrumbs__link`
- `table-of-contents__link`
- `hash-link`
- anchors within a docs article
- `theme-edit-this-page`
- `footer__link-item`

For the following selectors, we want to ensure that we always apply `text-decoration: none;` for all states:
- `pagination-nav__link`
- `navbar__brand`
- `dev-portal-link`
