### ISSUE TITLE
labels only available for not HTTPv2Tunnel

### ISSUE THREAD

**Issue by HugoGresse** [ngrok/ngrok-docs#481]
According to the doc, we should be able to set the labels on tunnels: https://ngrok.com/docs/agent/config/#labeled-tunnel-configuration 

So a config.yml like this: 
```
authtoken: xxxxxxxxxxxxx
region: eu
version: "2"
tunnels:
    api:
        labels:
         - edge=xxxxxxxxxxxxxxx
        addr: 3000
        proto: http
        domain: https://xxxxxxx.ngrok-free.app
```

should be doable, 

But it result in error : `field labels not found in type config.HTTPv2Tunnel` 
using `ngrok config check --config config.yml`

If this is expected, can the doc be clarified? 

`ngrok v3.4.0`
