### ISSUE TITLE
Invalid yaml in Request/Response Headers example config

### ISSUE THREAD

**Issue by jrobsonchase** [ngrok/ngrok-docs#497]
There shouldn't be commas after the "add" items in the response headers config:
```yaml
tunnels:
  example:
    proto: http
    addr: 80
    response_headers:
      add:
        - "content-security-policy: self",
        - "dial-duration: ${.backend.dial_duration}",
      remove:
        - "internal-trace-id"
```

Also in both the Request and Response Headers examples, the key shouldn't be plural, i.e. `request_header` vs `request_headers`.
