### ISSUE TITLE
host-header rewrite examples should be updated to use host header flag, instead of add headers

### ISSUE THREAD

**Issue by justngrok** [ngrok/ngrok-docs#730]
Rewriting the Host header examples use the add header syntax, instead of our special case host-header flag.
https://ngrok.com/docs/http/?cty=agent-config#rewrite-host-header

Examples should be updated with the correct syntax.

Example:
Agent Config Example 

```
tunnels:
  example:
    proto: http
    addr: 8080
    request_header:
      add: ["host: localhost"]
```
      
should be:

```
tunnels:
  example:
    proto: http
    addr: 8080
    host_header: localhost
```
