### ISSUE TITLE
Using ngrok with Docker compose -- clarify need for host.docker.internal in ngrok.yml on Mac

### ISSUE THREAD

**Issue by justngrok** [ngrok/ngrok-docs#734]
Need to update "Using ngrok with Docker Compose" to clarify that the defined tunnels in agent config needs to also use the host.docker.internal hostname for upstream.

https://ngrok.com/docs/using-ngrok-with/docker/

In the "Using ngrok with Docker", we do call out you have to use host.docker.internal for MacOS

This also applies to the upstream addr: for the ngrok.yml when following the Docker Compose instructions on mac.

> Note: for MacOS or Windows users, the --net=host option will not work. You will need to use the special url host.docker.internal as described in the [Docker networking documentation](https://docs.docker.com/desktop/mac/networking/#use-cases-and-workarounds).

Example:
```
tunnels:
  test:
    proto: http
    addr: http://host.docker.internal:80
```

This will allow docker to start, but returns ERR_NGROK_8012 (upstream error) when accessing the endpoint.
```
tunnels:
  test:
    proto: http
    addr: 80
```
